/* ===========================================================================
 * bqsm_debug.c — Weight Explorer & Equalizer endpoints for BQSM Server
 *
 *   Adds /debug endpoint with interactive weight visualization.
 *   Equalizer: 8-band weight amplifier per layer, with live preview.
 *   Heatmap: tensor weight distribution plots.
 * ======================================================================== */

static void handle_debug(int fd) {
    const char *html =
"HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\n\r\n"
"<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>BQSM Weight Explorer</title><style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:system-ui,monospace;background:#080810;color:#b0b8c8;overflow-x:hidden}"
".topbar{background:#0a0a18;border-bottom:1px solid #1a1a30;padding:10px 20px;display:flex;align-items:center;gap:16px}"
".topbar h1{font-size:16px;color:#58a6ff;white-space:nowrap}"
".topbar .info{font-size:11px;color:#484f58}"
".main{display:flex;height:calc(100vh - 48px)}"
".sidebar{width:320px;background:#0c0c1a;border-right:1px solid #1a1a30;overflow-y:auto;padding:12px}"
".content{flex:1;overflow-y:auto;padding:16px}"
".section{margin-bottom:16px}"
".section h3{font-size:12px;color:#58a6ff;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;border-bottom:1px solid #1a1a30;padding-bottom:4px}"
".eq-band{display:flex;align-items:center;gap:8px;margin:4px 0;padding:4px 8px;background:#0d0d1f;border-radius:4px;transition:background .2s}"
".eq-band:hover{background:#12122a}"
".eq-band .label{width:24px;font-size:10px;color:#58a6ff;text-align:right}"
".eq-band input[type=range]{flex:1;height:4px;-webkit-appearance:none;appearance:none;background:#1a1a30;border-radius:2px;outline:none}"
".eq-band input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:12px;height:12px;background:#58a6ff;border-radius:50%;cursor:pointer}"
".eq-band .val{width:28px;font-size:10px;color:#8b949e;text-align:center}"
".heatmap{display:grid;grid-template-columns:repeat(64,1fr);gap:1px;background:#0a0a18;border:1px solid #1a1a30;border-radius:4px;padding:4px;image-rendering:pixelated}"
".heatmap .cell{aspect-ratio:1;border-radius:1px;transition:background .3s}"
".cell.v0{background:#0a0a18}.cell.v1{background:#1a3050}.cell.v2{background:#3060a0}.cell.v3{background:#58a6ff}"
".layer-select{display:flex;gap:4px;flex-wrap:wrap;margin-bottom:8px}"
".layer-select button{background:#0d0d1f;border:1px solid #1a1a30;color:#8b949e;padding:4px 8px;font-size:10px;border-radius:3px;cursor:pointer}"
".layer-select button.active,.layer-select button:hover{background:#1a3050;color:#58a6ff;border-color:#3060a0}"
".preset-btn{display:block;width:100%;background:#0d0d1f;border:1px solid #1a1a30;color:#b0b8c8;padding:6px 10px;font-size:11px;border-radius:4px;cursor:pointer;margin:4px 0;text-align:left;transition:all .2s}"
".preset-btn:hover{background:#1a3050;border-color:#58a6ff}"
".preset-btn .emoji{font-size:14px;margin-right:6px}"
".preview{background:#0a0a18;border:1px solid #1a1a30;border-radius:4px;padding:12px;font-size:12px;line-height:1.6;min-height:60px;font-family:monospace;white-space:pre-wrap}"
".preview .layer-line{display:flex;gap:12px;align-items:center;margin:2px 0}"
".preview .bar{height:12px;background:#3060a0;border-radius:2px;transition:width .3s;min-width:1px}"
"</style></head><body>"
"<div class=\"topbar\"><h1>⚡ BQSM Weight Explorer</h1><span class=\"info\" id=\"model-info\">Loading...</span></div>"
"<div class=\"main\">"

/* Sidebar */
"<div class=\"sidebar\">"
"<div class=\"section\"><h3>Presets</h3>"
"<button class=\"preset-btn\" onclick=\"applyPreset('flat')\"><span class=\"emoji\">⚪</span>Flat (passthrough)</button>"
"<button class=\"preset-btn\" onclick=\"applyPreset('focus')\"><span class=\"emoji\">🎯</span>Focus (narrow attention)</button>"
"<button class=\"preset-btn\" onclick=\"applyPreset('dream')\"><span class=\"emoji\">🌊</span>Dream (wide creative)</button>"
"<button class=\"preset-btn\" onclick=\"applyPreset('sharp')\"><span class=\"emoji\">⚔️</span>Sharp (logical/analytical)</button>"
"<button class=\"preset-btn\" onclick=\"applyPreset('warm')\"><span class=\"emoji\">🔥</span>Warm (empathetic)</button>"
"<button class=\"preset-btn\" onclick=\"applyPreset('cold')\"><span class=\"emoji\">❄️</span>Cold (precise/clinical)</button>"
"</div>"

"<div class=\"section\"><h3>Equalizer — Layer <span id=\"eq-layer\">0</span></h3>"
"<div class=\"layer-select\" id=\"layer-btns\"></div>"
"<div id=\"equalizer\"></div>"
"</div>"

"<div class=\"section\"><h3>Query</h3>"
"<input id=\"prompt-input\" placeholder=\"Test prompt...\" style=\"width:100%;background:#0d0d1f;border:1px solid #1a1a30;color:#b0b8c8;padding:6px 8px;font-size:11px;border-radius:4px;margin-bottom:6px\" value=\"hello world\">"
"<button onclick=\"runInference()\" style=\"width:100%;background:#1f6feb;color:#fff;border:none;padding:8px;border-radius:4px;cursor:pointer;font-size:12px\">▶ Run Inference</button>"
"</div>"
"</div>"

/* Content */
"<div class=\"content\">"
"<div class=\"section\"><h3>Weight Heatmap</h3>"
"<div id=\"tensor-select\" style=\"display:flex;gap:4px;flex-wrap:wrap;margin-bottom:8px\"></div>"
"<div class=\"heatmap\" id=\"heatmap\"></div>"
"<div style=\"font-size:10px;color:#484f58;margin-top:4px\">Each pixel = 1 weight value (0-3). 64×N grid.</div>"
"</div>"
"<div class=\"section\"><h3>Inference Preview</h3>"
"<div class=\"preview\" id=\"preview\">Run inference to see per-layer activation...</div>"
"</div>"
"</div>"

"</div>"

"<script>"
"// State\n"
"let currentLayer=0, currentTensor=null;\n"
"let equalizer={}; for(let L=0;L<26;L++){equalizer[L]=[1,1,1,1,1,1,1,1];}\n"
"let modelInfo=null;\n"

"// Presets\n"
"const presets={\n"
"  flat:[1,1,1,1,1,1,1,1],\n"
"  focus:[2.0,1.5,1.0,0.5,0.3,0.5,1.0,1.5],\n"
"  dream:[0.3,0.5,1.0,1.5,2.0,1.5,1.0,0.5],\n"
"  sharp:[2.0,2.0,1.0,0.3,0.1,0.3,1.0,2.0],\n"
"  warm:[0.5,1.0,2.0,2.0,1.5,1.0,0.5,0.3],\n"
"  cold:[2.0,1.0,0.3,0.3,0.5,1.0,1.5,2.0],\n"
"};\n"

"async function init(){\n"
"  try{\n"
"    const r=await fetch('/health');\n"
"    modelInfo=await r.json();\n"
"    document.getElementById('model-info').textContent=\n"
"      `d=${modelInfo.d_model} FFN=${modelInfo.ffn_dim} layers=${modelInfo.n_layers} | ${modelInfo.model}`;\n"
"    buildLayerButtons();\n"
"    buildEqualizer();\n"
"    buildTensorSelect();\n"
"    loadHeatmap('blk.0.ffn_down.weight');\n"
"  }catch(e){document.getElementById('model-info').textContent='Error: '+e.message;}\n"
"}\n"

"function buildLayerButtons(){\n"
"  const n=modelInfo?.n_layers||26;\n"
"  const c=document.getElementById('layer-btns');\n"
"  for(let i=0;i<n;i++){\n"
"    const b=document.createElement('button');\n"
"    b.textContent=i; b.onclick=()=>selectLayer(i);\n"
"    if(i===currentLayer)b.className='active';\n"
"    c.appendChild(b);\n"
"  }\n"
"}\n"

"function selectLayer(L){\n"
"  currentLayer=L;\n"
"  document.getElementById('eq-layer').textContent=L;\n"
"  document.querySelectorAll('#layer-btns button').forEach((b,i)=>b.className=i===L?'active':'');\n"
"  buildEqualizer();\n"
"}\n"

"function buildEqualizer(){\n"
"  const c=document.getElementById('equalizer');\n"
"  c.innerHTML='';\n"
"  const bands=['α','β','γ','δ','ε','ζ','η','θ'];\n"
"  const labels=['FFN 0-1K','1-2K','2-3K','3-4K','4-5K','5-6K','6-7K','7-9K'];\n"
"  for(let i=0;i<8;i++){\n"
"    const v=equalizer[currentLayer][i];\n"
"    const d=document.createElement('div');d.className='eq-band';\n"
"    d.innerHTML=`<span class=\"label\">${bands[i]}</span>`\n"
"      +`<input type=\"range\" min=\"0\" max=\"3\" step=\"0.1\" value=\"${v}\" oninput=\"updateBand(${i},this.value)\" title=\"${labels[i]}\">`\n"
"      +`<span class=\"val\">${v.toFixed(1)}</span>`;\n"
"    c.appendChild(d);\n"
"  }\n"
"}\n"

"function updateBand(i,v){\n"
"  equalizer[currentLayer][i]=parseFloat(v);\n"
"  document.querySelectorAll('#equalizer .val')[i].textContent=parseFloat(v).toFixed(1);\n"
"}\n"

"function applyPreset(name){\n"
"  equalizer[currentLayer]=[...presets[name]];\n"
"  buildEqualizer();\n"
"}\n"

"function buildTensorSelect(){\n"
"  const tensors=['ffn_down.weight','ffn_gate.weight','ffn_up.weight','attn_q.weight','attn_k.weight','attn_v.weight','attn_output.weight'];\n"
"  const c=document.getElementById('tensor-select');\n"
"  tensors.forEach(t=>{\n"
"    const b=document.createElement('button');\n"
"    b.textContent=t.replace('.weight',''); b.style.cssText='background:#0d0d1f;border:1px solid #1a1a30;color:#8b949e;padding:4px 8px;font-size:10px;border-radius:3px;cursor:pointer';\n"
"    b.onclick=()=>loadHeatmap(`blk.${currentLayer}.${t}`);\n"
"    c.appendChild(b);\n"
"  });\n"
"}\n"

"async function loadHeatmap(name){\n"
"  currentTensor=name;\n"
"  try{\n"
"    const r=await fetch(`/debug/tensor?name=${encodeURIComponent(name)}&max=1024`);\n"
"    const data=await r.json();\n"
"    const c=document.getElementById('heatmap');\n"
"    const W=64, H=Math.min(32,Math.ceil(data.values.length/W));\n"
"    c.style.gridTemplateColumns=`repeat(${W},1fr)`;\n"
"    c.innerHTML='';\n"
"    for(let i=0;i<W*H;i++){\n"
"      const cell=document.createElement('div');\n"
"      cell.className=`cell v${data.values[i]||0}`;\n"
"      c.appendChild(cell);\n"
"    }\n"
"  }catch(e){console.error(e);}\n"
"}\n"

"async function runInference(){\n"
"  const prompt=document.getElementById('prompt-input').value||'test';\n"
"  const preview=document.getElementById('preview');\n"
"  preview.textContent='Running...';\n"
"  try{\n"
"    const eq={}; for(let L=0;L<(modelInfo?.n_layers||26);L++) eq[L]=equalizer[L]||equalizer[currentLayer];\n"
"    const r=await fetch('/debug/infer',{\n"
"      method:'POST',\n"
"      headers:{'Content-Type':'application/json'},\n"
"      body:JSON.stringify({prompt,equalizer:eq,layers:Math.min(6,modelInfo?.n_layers||26)})\n"
"    });\n"
"    const data=await r.json();\n"
"    let html='';\n"
"    if(data.layers){\n"
"      const maxAct=Math.max(...data.layers.map(l=>l.mean),1);\n"
"      data.layers.forEach(l=>{\n"
"        const w=Math.max(1,(l.mean/maxAct)*200);\n"
"        html+=`<div class=\"layer-line\">L${l.layer.toString().padStart(2)}: <div class=\"bar\" style=\"width:${w}px\"></div> ${l.mean.toFixed(3)}</div>`;\n"
"      });\n"
"    }\n"
"    if(data.eq_applied)html+=`\\nEqualizer applied to ${data.eq_applied} layers`;\n"
"    if(data.time_ms)html+=`\\n${data.time_ms}ms | ${data.gmac?.toFixed(2)||0} GMAC`;\n"
"    preview.innerHTML=html||'No data';\n"
"  }catch(e){preview.textContent='Error: '+e.message;}\n"
"}\n"

"init();\n"
"</script></body></html>";

    write(fd, html, strlen(html));
}