/* ===========================================================================
 * bqsm_inference.c — BQSM Quantized Inference Engine (v2)
 * ===========================================================================
 *
 *   Loads model.h (generated by bqsm_nn.py) and runs batched inference
 *   with pure int8 table lookups. No floating point during forward pass.
 *
 * BUILD:  cc -O3 -march=native -std=c11 bqsm_inference.c -o bqsm_inf -lm
 * RUN:    ./bqsm_inf 256 10000
 *
 * The transition table encodes: tt[input_q][w_idx] = contribution
 * where w_idx = weight + 1 ∈ {0,1,2} for weights {-1,0,+1}.
 * Contributions CAN be negative (signed int8).
 * ======================================================================== */

#define _POSIX_C_SOURCE 199309L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>

/* Include the generated model */
#include "model.h"

/* --- Batched inference -------------------------------------------------- */
/*     input_batch:  [n_samples * n_in],  int8_t  (q values 0..q_max)       */
/*     output_batch: [n_samples * n_out], int8_t                            */

static void infer_batch(const int8_t (*tt)[3],
                        const int8_t *input_batch,
                        int8_t *output_batch,
                        int n_samples,
                        int q_max_out)
{
    /* Max neurons across all layers */
    int max_dim = N_IN_0;
    if (N_OUT_0 > max_dim) max_dim = N_OUT_0;
#if N_LAYERS > 1
    if (N_IN_1 > max_dim) max_dim = N_IN_1;
    if (N_OUT_1 > max_dim) max_dim = N_OUT_1;
#endif

    int8_t *state = malloc(n_samples * max_dim);
    int8_t *next  = malloc(n_samples * max_dim);
    if (!state || !next) { free(state); free(next); return; }

    /* Load input into working state */
        for (int s = 0; s < n_samples; s++)
            for (int i = 0; i < N_IN_0; i++)
                state[s * N_IN_0 + i] = input_batch[s * N_IN_0 + i] > q_max_out
                                         ? q_max_out : input_batch[s * N_IN_0 + i];

    /* Layer 0 */
    {
        for (int s = 0; s < n_samples; s++) {
            for (int j = 0; j < N_OUT_0; j++) {
                int32_t acc = b0[j];
                for (int i = 0; i < N_IN_0; i++) {
                    int q = state[s * N_IN_0 + i];
                    int w_idx = w0[j * N_IN_0 + i] + 1;  /* {-1,0,1}→{0,1,2} */
                    if (q >= 0 && q <= TT_Q_MAX && w_idx >= 0 && w_idx <= 2)
                        acc += tt[q][w_idx];
                }
                if (acc < 0) acc = 0;
                if (acc > q_max_out) acc = q_max_out;
                next[s * N_OUT_0 + j] = (int8_t)acc;
            }
        }
        memcpy(state, next, n_samples * N_OUT_0);
    }

#if N_LAYERS > 1
    /* Layer 1 */
    {
        for (int s = 0; s < n_samples; s++) {
            for (int j = 0; j < N_OUT_1; j++) {
                int32_t acc = b1[j];
                for (int i = 0; i < N_IN_1; i++) {
                    int q = state[s * N_IN_1 + i];
                    int w_idx = w1[j * N_IN_1 + i] + 1;
                    if (q >= 0 && q <= TT_Q_MAX && w_idx >= 0 && w_idx <= 2)
                        acc += tt[q][w_idx];
                }
                if (acc < 0) acc = 0;
                if (acc > q_max_out) acc = q_max_out;
                next[s * N_OUT_1 + j] = (int8_t)acc;
            }
        }
        memcpy(output_batch, next, n_samples * N_OUT_1);
    }
#else
    memcpy(output_batch, state, n_samples * N_OUT_0);
#endif

    free(state); free(next);
}

/* --- Benchmark ----------------------------------------------------------- */

static double now_sec(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec + 1e-9 * (double)ts.tv_nsec;
}

static void gen_input(int8_t *buf, int n_samples, int n_in, int q_max_in) {
    for (int i = 0; i < n_samples * n_in; i++)
        buf[i] = (int8_t)(rand() % (q_max_in + 1));
}

int main(int argc, char **argv) {
    int batch_size = argc > 1 ? atoi(argv[1]) : 256;
    int n_batches  = argc > 2 ? atoi(argv[2]) : 10000;

    printf("=== BQSM Inference Engine — XOR Model ===\n");
    printf("T7400 Xeon X5472 (SSE4.1, 8-core Harpertown, 3.0 GHz)\n\n");

    /* --- Verification on known XOR patterns ------------------------------ */
    printf("XOR Verification:\n");
    int8_t test_in[4 * 2] = {0,0, 0,1, 1,0, 1,1};
    int8_t test_out[4];
    infer_batch(tt_model, test_in, test_out, 4, 2);

    const char *expected[4] = {"0","1","1","0"};
    int ok = 0;
    for (int i = 0; i < 4; i++) {
        int correct = (test_out[i] == atoi(expected[i]));
        ok += correct;
        printf("  (%d,%d) → q=%d  (expect %s)  %s\n",
               test_in[i*2], test_in[i*2+1], test_out[i], expected[i],
               correct ? "✓" : "✗");
    }
    printf("  %d/4 correct  %s\n\n", ok, ok == 4 ? "PASS" : "FAIL");

    /* --- Benchmark ------------------------------------------------------- */
    int n_in = N_IN_0;
    srand(42);

    int8_t *input  = malloc(batch_size * n_in);
    int8_t *output = malloc(batch_size);
    if (!input || !output) { fprintf(stderr, "alloc\n"); return 1; }

    printf("Benchmark: %d samples/batch × %d batches\n", batch_size, n_batches);

    double t0 = now_sec();
    long total = 0;

    for (int b = 0; b < n_batches; b++) {
        gen_input(input, batch_size, n_in, 2);  /* ternary input q∈{0,1,2} */
        infer_batch(tt_model, input, output, batch_size, 2);
        total += batch_size;

        if (b == 0 || b == n_batches - 1) {
            double el = now_sec() - t0;
            printf("  batch %5d/%d  %.0f inf/s  (%.1f µs/inf)\n",
                   b+1, n_batches, total/el, 1e6*el/total);
        }
    }

    double total_t = now_sec() - t0;
    printf("\n─────────────────────────────────────────────\n");
    printf("Total: %ld inferences in %.4fs\n", total, total_t);
    printf("Throughput: %.0f inf/s  (%.1f µs/inf)\n",
           total/total_t, 1e6*total_t/total);

    /* Throughput scaling */
    printf("\nSCALING (T7400, 8 cores, SSE4.1):\n");
    printf("  Single-core:          %.0f inf/s\n", total/total_t);
    printf("  SSE4.1 auto-vec (4×): ~%.0f inf/s\n", 4.0*total/total_t);
    printf("  8-core parallel:      ~%.0f inf/s\n", 8.0*total/total_t);

    /* Model stats */
    printf("\nModel: %d layers, %d→%d→%d\n", N_LAYERS, N_IN_0, N_OUT_0, N_OUT_1);
    printf("  Params: %d weights (%d bytes) + %d biases\n",
           N_IN_0*N_OUT_0 + N_IN_1*N_OUT_1,
           N_IN_0*N_OUT_0 + N_IN_1*N_OUT_1,
           N_OUT_0 + N_OUT_1);
    printf("  TT: %d entries × 1 byte = %lu bytes (L1d resident)\n",
           (TT_Q_MAX+1)*3, sizeof(tt_model));
    printf("  Ops/inf: %d table lookups\n",
           N_IN_0*N_OUT_0 + N_IN_1*N_OUT_1);

    free(input); free(output);
    return ok == 4 ? 0 : 1;
}