/* Auto-generated by bqsm_nn.py — BQSM inference model */
/* Transition table: signed contributions per (input_q, weight) */

#ifndef BQSM_MODEL_H
#define BQSM_MODEL_H

#include <stdint.h>

/* Transition table: tt[q][w+1] where w ∈ {-1,0,+1}, q ∈ {0..3} */
#define TT_Q_MAX 3
#define TT_DEFINED 1
static const int8_t tt_model[4][3] = {
    {0, 0, 0},
    {-1, 0, 1},
    {-2, 0, 2},
    {-3, 0, 3},
};

/* Layer 0: 2 → 4 */
#define N_IN_0 2
#define N_OUT_0 4
static const int8_t w0[8] = {1, 1, 1, -1, -1, 1, -1, -1};
static const int32_t b0[4] = {-1, 0, 0, 1};

/* Layer 1: 4 → 1 */
#define N_IN_1 4
#define N_OUT_1 1
static const int8_t w1[4] = {0, 1, 1, 0};
static const int32_t b1[1] = {0};

#define N_LAYERS 2

#endif /* BQSM_MODEL_H */
